spring.application.name: dhee_program
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
#数据库连接的url
spring.datasource.url: jdbc:mysql://localhost:3306/homework
  #连接数据库的用户名
spring.datasource.username: root
  #连接数据库的密码
spring.datasource.password: 1234
